version: "3.9"
services:
  node1:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: 'node1'
    ports:
      - "127.0.0.2:8002:22"
  node2:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: 'node2'
    ports:
      - "127.0.0.3:8003:22"
  node3:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: 'node3'
    ports:
      - "127.0.0.4:8004:22"

